services:
  - type: web
    name: minecraft-bot
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLOUD_ENV
        value: "true" 